swiftmailer:
    transport: gmail
    auth_mode: login
    port: 465
    # port: 587
    host: smtp.gmail.com
    username: 'taccdev44@gmail.com'
    password: 't4p4$Dm3'
    spool: { type: 'memory' }