# index:
#    path: /login
#    controller: App\Controller\DefaultController::index

#Si se establece esta ruta por defecto, no te permite loguearte
#index:
#   path: /
#   controller: App\Controller\SecurityController::login
